language: php

sudo: false

php:
    - 5.5
    - 5.6
    - 7.0

notifications:
    email: dev@anime-db.org

before_install:
    - if [[ -n "$GH_TOKEN" ]]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install:
    - composer install --prefer-dist --no-interaction --no-progress

script:
    - vendor/bin/phpunit --coverage-clover build/coverage-clover.xml
    - for file in tests/functional/*; do php -f $file; done

after_script:
    - vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage-clover.xml
    - vendor/bin/coveralls -v -c .coveralls.yml
