language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

notifications:
    email: dev@anime-db.org

install:
    - composer self-update
    - composer install --prefer-source --dev --no-interaction

script:
    - phpunit --verbose --coverage-clover=coverage.clover
    - php -f tests/functional/simple_schedule.php
    - php -f tests/functional/build_schedule.php

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
