language: php

sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

notifications:
    email: dev@anime-db.org

before_install:
  - composer self-update
  - 'if [[ -n "$GH_TOKEN" ]]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;'

install:
    - composer install --prefer-source --dev --no-interaction

script:
    - phpunit --verbose --coverage-clover=coverage.clover
    - for file in tests/functional/*; do php -f $file; done

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
